# Generated by Django 6.0.5 on 2026-05-16 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("id_rol", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_rol", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "roles",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("correo", models.CharField(max_length=150, unique=True)),
                ("contrasena", models.CharField(max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "id_rol",
                    models.ForeignKey(
                        db_column="id_rol",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usuarios.rol",
                    ),
                ),
            ],
            options={
                "db_table": "usuarios",
                "managed": True,
            },
        ),
    ]
